---
- name: Install haproxy on the haproxy vm
  hosts: all
  become: yes

  tasks:
    - name: Gather nginx hostnames and IP addresses
      set_fact: 
        haproxy_backend_servers: "{{ haproxy_backend_servers|default([]) + [ mydict ]  }}"
      vars:
        mydict:
          name: "{{ ansible_facts.hostname }}"
          address: "{{ ansible_facts.default_ipv4.address }}"
      when: '"tag_Ansible_nginx" in group_names'

    - name: Show the calculated fact
      debug:
        var: haproxy_backend_servers

  # roles:
  #   - geerlingguy.haproxy